const int n1 = 7;
const long n2 = 44;
const float n3 = 1.5F;
const double n4 = 21.21;
const decimal n5 = 2.3M;
const bool n6 = false;
const char n7 = 'H';
const string n8 = "2021050894";
Console.WriteLine(n1);
Console.WriteLine(n2);
Console.WriteLine(n3);
Console.WriteLine(n4);
Console.WriteLine(n5);
Console.WriteLine(n6);
Console.WriteLine(n7);
Console.WriteLine(n8);