Console.WriteLine ("Nhap so thu nhat");
int a = Convert.ToInt32(Console.ReadLine());
Console.WriteLine ("Nhap so thu hai");
int b = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Tich cua {0} va {1} là {2}",a,b,a*b);
Console.WriteLine("Thuong cua {0} va {1} là {2}",a,b,a/b);
Console.WriteLine("Hieu cua {0} va {1} là {2}",a,b,a-b);
Console.WriteLine("So du cua {0} va {1} là {2}",a,b,a%b);
Console.WriteLine("Ngo Linh Chi");
Console.WriteLine("2021050894");